name: Update Build Time

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write  # 关键：允许写权限

jobs:
  update-time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Update build time
        run: |
          TIME=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
          sed -i "s/<!--BUILD_TIME-->.*<!--\/BUILD_TIME-->/<!--BUILD_TIME-->$TIME<!--\/BUILD_TIME-->/" readme.md

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add readme.md
          git commit -m "chore: update build time $TIME" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
