name: Update Build Time

on:
  schedule:
    - cron: '*/1 * * * *'  # 每分钟运行
  workflow_dispatch:       # 允许手动触发

jobs:
  update-time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Update build time
        run: |
          TIME=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
          sed -i "s/<!--BUILD_TIME-->.*<!--\/BUILD_TIME-->/<!--BUILD_TIME-->$TIME<!--\/BUILD_TIME-->/" readme.md

      - name: Commit and push changes
        run: |
          git add readme.md
          git commit -m "chore: update build time $TIME" || echo "No changes to commit"
          git push
